import { IMAGES } from './images'

export const blogPosts = [
  {
    id: 1,
    slug: 'presbyond-glasses-free-vision',
    image: IMAGES.blog1,
    tag: 'Treatment Guides',
    tagClass: 'tag-treatment-guides',
    title: 'Rediscover Your Freedom: Presbyond for Glasses-Free Vision After 40',
    excerpt: 'Imagine a world without the constant struggle of searching for your glasses, the frustration of fogged lenses, or the limitations imposed by progressive lenses.',
    author: 'Dr. Aadithreya Varman',
    date: 'Jan 23, 2025',
    readTime: '6 min read',
    category: 'treatment-guides',
    content: [
      'Imagine a world without the constant struggle of searching for your glasses, the frustration of fogged lenses, or the limitations imposed by progressive lenses. For millions of people over the age of 40, presbyopia — the gradual loss of the eye\'s ability to focus on nearby objects — is an inevitable part of ageing.',
      '## What Is Presbyopia?',
      'Presbyopia is a completely natural part of ageing. As we get older, the lens inside the eye gradually loses its flexibility, making it harder to focus on close-up objects. By the age of 45, almost everyone experiences some degree of presbyopia, typically reaching for reading glasses or bifocals.',
      '## How PRESBYOND Works',
      'PRESBYOND (developed by Carl Zeiss) is a laser blended vision technique that adjusts each eye slightly differently:\n\n- **The dominant eye** is corrected for distance vision\n- **The non-dominant eye** is corrected for near vision\n- A unique **blend zone** is created where the two focal points overlap\n\nThe brain seamlessly merges the images from both eyes, providing a continuous range of clear vision from near to far — without the jarring transition of traditional monovision.',
      '## Am I a Candidate?',
      'PRESBYOND may be suitable if you:\n\n- Are over 40 years old\n- Rely on reading glasses for close-up tasks\n- Want to reduce or eliminate dependence on glasses\n- Have healthy eyes with no significant disease\n\nA comprehensive assessment including corneal mapping, wavefront analysis, and dominant eye testing will confirm your suitability.',
      '## The Procedure',
      'PRESBYOND is a quick outpatient procedure:\n\n1. Anaesthetic eye drops are applied — no injections\n2. The laser treatment takes approximately 30 seconds per eye\n3. Both eyes are treated in a single session\n4. Total time in the laser suite: about 15 minutes',
      '## Recovery and Results',
      'Most patients notice improved vision within 24 hours. The blend zone adaptation typically takes 1–2 weeks as your brain learns to merge the images. Over 97% of patients achieve functional near and distance vision without glasses.',
      '## Is PRESBYOND Right for You?',
      'At Uma Eye Clinic, we have helped hundreds of patients over 40 regain their visual independence. Book a consultation to find out if PRESBYOND can work for you.',
    ]
  },
  {
    id: 2,
    slug: 'smile-and-smile-pro',
    image: IMAGES.blog2,
    tag: 'Treatment Guides',
    tagClass: 'tag-treatment-guides',
    title: 'SMILE and SMILE Pro: The Evolution of Vision Correction',
    excerpt: 'At Uma Eye Clinic in Anna Nagar, Chennai, we\'ve always been committed to providing our patients with the most advanced and effective vision correction.',
    author: 'Dr. Aadithreya Varman',
    date: 'Dec 31, 2024',
    readTime: '7 min read',
    category: 'treatment-guides',
    content: [
      'At Uma Eye Clinic in Anna Nagar, Chennai, we\'ve always been committed to providing our patients with the most advanced and effective vision correction treatments available. SMILE and SMILE Pro represent the evolution of laser vision correction technology.',
      '## What Is SMILE?',
      'SMILE (Small Incision Lenticule Extraction) is a minimally invasive laser vision correction procedure. Unlike LASIK, which requires creating a corneal flap, SMILE works through a tiny keyhole incision of just 2mm.',
      '## How SMILE Pro Works',
      'SMILE PRO is the latest evolution in laser vision correction, using the Zeiss VisuMax 800. Instead of creating a flap:\n\n1. A femtosecond laser creates a tiny disc-shaped piece of tissue (lenticule) within the cornea\n2. The lenticule is removed through a small 2mm incision\n3. This reshapes the cornea and corrects the vision — all in just 9 seconds per eye',
      '## Key Advantages of SMILE and SMILE Pro',
      '**Minimally invasive:** No flap creation means greater corneal stability.\n\n**Reduced dry eye risk:** SMILE preserves more corneal nerves, resulting in significantly less dry eye post-surgery.\n\n**Quick recovery:** Most patients report comfortable vision within hours.\n\n**Fast procedure:** SMILE Pro takes just 9 seconds of laser time per eye.\n\n**Ideal for active lifestyles:** No flap-related concerns for sports and physical activities.',
      '## Who Is a Good Candidate?',
      'SMILE and SMILE Pro are ideal for patients who:\n- Have moderate to high myopia\n- Want the most minimally invasive option\n- Have dry eye concerns\n- Lead an active lifestyle (sports, swimming)\n- Are looking for a flapless procedure',
      '## Our Commitment',
      'At Uma Eye Clinic, we offer the latest in vision correction technology and our specialists will recommend the best option based on your eye anatomy, prescription, lifestyle, and personal preferences. Book a consultation to find out which treatment is right for you.',
    ]
  },
  {
    id: 3,
    slug: 'smile',
    image: IMAGES.blog3,
    tag: 'Treatment Guides',
    tagClass: 'tag-treatment-guides',
    title: 'SMILE! Everything About Small Incision Lenticule Extraction',
    excerpt: 'SMILE is the most recent and advanced form of laser-assisted refractive surgery. SMILE stands for \'Small Incision Lenticule Extraction\'.',
    author: 'Dr. N.V. Arulmozhi Varman',
    date: 'Dec 3, 2024',
    readTime: '6 min read',
    category: 'treatment-guides',
    content: [
      'SMILE is the most recent and advanced form of laser-assisted refractive surgery. SMILE stands for \'Small Incision Lenticule Extraction\'. It represents a significant advancement in how we correct vision problems like myopia (short-sightedness) and astigmatism.',
      '## How Does SMILE Work?',
      'SMILE uses a femtosecond laser to create a small, lens-shaped piece of tissue (called a lenticule) within the cornea. This lenticule is then removed through a tiny incision of just 2-4mm, reshaping the cornea and correcting the refractive error.',
      '## Advantages Over Traditional Methods',
      'Compared to LASIK and PRK, SMILE offers several key advantages:\n\n- **Flapless procedure** — No corneal flap is created, maintaining greater corneal structural integrity\n- **Smaller incision** — Just 2-4mm compared to the ~20mm flap in LASIK\n- **Less dry eye** — More corneal nerves are preserved\n- **Quick recovery** — Most patients see well within 24 hours\n- **Suitable for active lifestyles** — No flap displacement risk during sports',
      '## Who Can Benefit from SMILE?',
      'SMILE is particularly well-suited for patients with:\n\n- Myopia (short-sightedness) up to -10 dioptres\n- Astigmatism up to -5 dioptres\n- Those who want a minimally invasive procedure\n- Active individuals and athletes\n- Patients concerned about dry eye',
      '## The Procedure Experience',
      'The entire SMILE procedure typically takes about 10-15 minutes for both eyes. The actual laser application is just a few seconds per eye. Most patients experience minimal discomfort and can return to normal activities within a day or two.',
      '## Results',
      'SMILE has shown excellent results in clinical studies worldwide, with the vast majority of patients achieving 20/20 vision or better. The procedure has been performed on millions of eyes globally with an outstanding safety profile.',
    ]
  },
  {
    id: 4,
    slug: 'lasik-guide',
    image: IMAGES.blog4,
    tag: 'Treatment Guides',
    tagClass: 'tag-treatment-guides',
    title: 'LASIK: A Complete Guide to Laser Vision Correction',
    excerpt: 'Individuals wearing glasses to see clearly can have their glasses removed and have perfect vision without glasses.',
    author: 'Dr. N.V. Arulmozhi Varman',
    date: 'Dec 3, 2024',
    readTime: '7 min read',
    category: 'treatment-guides',
    content: [
      'Individuals wearing glasses to see clearly can have their glasses removed and have perfect vision without glasses. LASIK (Laser-Assisted In Situ Keratomileusis) has been the gold standard in refractive surgery for over two decades, helping millions of people achieve freedom from glasses and contact lenses.',
      '## What Is LASIK?',
      'LASIK is a laser eye surgery that permanently changes the shape of the cornea to correct refractive errors including myopia (near-sightedness), hyperopia (far-sightedness), and astigmatism. The procedure involves two steps:\n\n1. A femtosecond laser creates a thin flap on the corneal surface\n2. An excimer laser reshapes the underlying corneal tissue to correct the refractive error\n3. The flap is repositioned and heals naturally',
      '## Who Is a Good Candidate?',
      'LASIK may be right for you if:\n\n- You are over 18 years old\n- Your prescription has been stable for at least one year\n- You have sufficient corneal thickness\n- Your eyes are generally healthy\n- You want to reduce or eliminate dependence on glasses or contact lenses',
      '## The Procedure',
      'The LASIK procedure is quick and painless:\n\n1. Anaesthetic eye drops are applied\n2. A femtosecond laser creates a precise corneal flap\n3. The excimer laser reshapes the cornea in about 30 seconds\n4. The flap is gently repositioned\n5. Total procedure time: approximately 15 minutes for both eyes',
      '## Recovery and Results',
      'Most patients notice significantly improved vision within hours of the procedure. Full visual recovery typically occurs within 24-48 hours. The vast majority of LASIK patients achieve 20/20 vision or better.',
      '## Safety and Track Record',
      'LASIK has an outstanding safety profile with over 30 years of clinical evidence. At Uma Eye Clinic, our experienced surgeons use the latest technology to ensure optimal outcomes for every patient.',
    ]
  },
  {
    id: 5,
    slug: 'glaucoma-silent-thief',
    image: IMAGES.blog5,
    tag: 'Eye Health',
    tagClass: 'tag-eye-health',
    title: 'GLAUCOMA: Understanding the Silent Thief of Sight',
    excerpt: 'The eye is a fluid filled structure. The fluid inside the eye gives a normal pressure to the eye. The increase in eye pressure due to various reasons damages the nerve of the eye.',
    author: 'Dr. N.V. Arulmozhi Varman',
    date: 'Dec 3, 2024',
    readTime: '6 min read',
    category: 'eye-health',
    content: [
      'The eye is a fluid filled structure. The fluid inside the eye gives a normal pressure to the eye. The increase in eye pressure due to various reasons damages the nerve of the eye. This condition is known as glaucoma, and it is one of the leading causes of irreversible blindness worldwide.',
      '## Why Is Glaucoma Called the Silent Thief of Sight?',
      'Glaucoma is called the "silent thief of sight" because it often progresses without symptoms until significant vision loss has occurred. In the early stages, there is typically no pain and no noticeable change in vision. By the time patients notice vision problems, the damage is often irreversible.',
      '## Types of Glaucoma',
      'There are several types of glaucoma:\n\n- **Open-angle glaucoma** — The most common form, developing slowly over time\n- **Angle-closure glaucoma** — Can develop suddenly and is a medical emergency\n- **Normal-tension glaucoma** — Optic nerve damage occurs despite normal eye pressure\n- **Secondary glaucoma** — Caused by other conditions such as injury, inflammation, or medication',
      '## Risk Factors',
      'You may be at higher risk for glaucoma if you:\n\n- Are over 40 years old\n- Have a family history of glaucoma\n- Have high eye pressure (intraocular pressure)\n- Are diabetic\n- Have high myopia (short-sightedness)\n- Have been using steroid medications for extended periods',
      '## Detection and Diagnosis',
      'Regular comprehensive eye examinations are crucial for early detection. At Uma Eye Clinic, we use advanced diagnostic tools including OCT (Optical Coherence Tomography) scans of the optic nerve head and visual field testing to detect glaucoma at its earliest stages.',
      '## Treatment Options',
      'While glaucoma damage cannot be reversed, early detection and treatment can slow or prevent further vision loss. Treatment options include:\n\n- **Eye drops** — To reduce eye pressure\n- **Laser treatment** — To improve fluid drainage\n- **Surgery** — When other treatments are insufficient\n\nRegular follow-up is essential to monitor the condition and adjust treatment as needed.',
      '## The Importance of Early Detection',
      'Since glaucoma often has no early symptoms, regular eye check-ups are the best defence. We recommend comprehensive eye examinations at least once a year, especially if you have risk factors for glaucoma.',
    ]
  },
  {
    id: 6,
    slug: 'digital-eye-strain',
    image: IMAGES.blog6,
    tag: 'Eye Health',
    tagClass: 'tag-eye-health',
    title: 'Digital Eye Strain: Protecting Your Vision in a Screen-First World',
    excerpt: 'Practical tips and expert recommendations for reducing eye fatigue and protecting long-term eye health in the digital age.',
    author: 'Dr. Uma Mallaiah',
    date: 'Feb 8, 2026',
    readTime: '5 min read',
    category: 'eye-health',
    content: [
      'In today\'s world, most of us spend 8–10 hours a day staring at screens — computers, smartphones, tablets, and televisions. This prolonged digital exposure has led to a surge in a condition known as digital eye strain, or computer vision syndrome.',
      '## What Is Digital Eye Strain?',
      'Digital eye strain is a group of eye and vision-related problems that result from prolonged screen use. Symptoms include:\n\n- Eye fatigue and discomfort\n- Dry, irritated eyes\n- Blurred vision\n- Headaches\n- Neck and shoulder pain\n- Difficulty focusing between near and far objects',
      '## Why Screens Strain Your Eyes',
      'Several factors contribute to digital eye strain:\n\n**Reduced blinking:** We blink about 66% less when looking at screens, leading to dry eyes.\n\n**Blue light exposure:** Screens emit high-energy blue light that can contribute to eye fatigue.\n\n**Poor ergonomics:** Incorrect screen distance, angle, or lighting creates additional strain.\n\n**Small text and glare:** Squinting at small fonts or fighting screen glare forces your eye muscles to work harder.',
      '## The 20-20-20 Rule',
      'The simplest and most effective strategy: every 20 minutes, look at something 20 feet away for 20 seconds. This relaxes the focusing muscles inside your eyes and encourages blinking.',
      '## Expert Tips for Screen Users',
      '1. **Position your screen correctly** — The top of your monitor should be at or slightly below eye level, about an arm\'s length away.\n2. **Adjust brightness and contrast** — Match your screen brightness to your surroundings.\n3. **Use artificial tears** — Preservative-free lubricating drops can help if you experience dryness.\n4. **Optimise your workspace lighting** — Reduce glare by using curtains or an anti-glare screen filter.\n5. **Consider blue light filtering** — Blue light glasses or screen filters may help reduce fatigue.\n6. **Take regular breaks** — Stand up, stretch, and look away from the screen every 30 minutes.',
      '## When to See an Eye Doctor',
      'If symptoms persist despite following these tips, you may have an underlying refractive error or dry eye condition that needs treatment. A comprehensive eye examination at Uma Eye Clinic can identify the root cause and provide targeted solutions.',
    ]
  }
]
