// Image mapping for Uma Eye Clinic
export const IMAGES = {
  // Brand
  logo: '/logo.svg',

  // Home page
  heroBanner: '/images/home/umaeye-banner.webp',
  heroBanner2: '/images/home/umaeye-banner-2.webp',
  heroBanner3: '/images/home/umaeye-banner-3.webp',
  heroBanner4: '/images/home/umaeye-banner-4.webp',
  aboutSnapshot: '/images/home/about-right.webp',
  doctorHome1: '/images/home/our-team/team-member-1.webp',
  doctorHome2: '/images/home/our-team/team-member-3.webp',
  doctorHome3: '/images/home/our-team/team-member-4.webp',
  doctorHome4: '/images/home/our-team/team-member-7.webp',
  doctorHome5: '/images/home/our-team/team-member-9.webp',
  doctorHome6: '/images/home/our-team/team-member-10.webp',
  doctorHome7: '/images/home/our-team/team-member-11.webp',
  doctorHome8: '/images/doctors/team-member-11.webp',
  opticalShowroom: '/images/about/optical-showroom-1.webp',
  blogHome1: '/images/home/blogs/blog-1.webp',
  blogHome2: '/images/home/blogs/blog-2.webp',
  blogHome3: '/images/home/blogs/blog-3.webp',
  award1: '/images/home/award-1.webp',
  award2: '/images/home/award-2.webp',
  award3: '/images/home/award-3.webp',
  videoHome1: '/images/home/video/video-1.webp',
  videoHome2: '/images/home/video/video-2.webp',
  videoHome3: '/images/home/video/video-3.webp',
  videoHome4: '/images/home/video/video-4.webp',
  videoHome5: '/images/home/video/video-5.webp',
  vision1: '/images/home/vision-1.webp',
  vision2: '/images/home/vision-2.webp',
  vision3: '/images/home/vision-3.webp',

  // About page
  aboutHero: '/images/about/about-banner.webp',
  aadithreya: '/images/about/aadithreya.webp',
  equipment1: '/images/about/investigate-1.webp',
  equipment2: '/images/about/investigate-2.webp',
  equipment3: '/images/about/investigate-3.webp',
  equipment4: '/images/about/investigate-4.webp',
  imageSurgery: '/images/about/image-surgery.webp',
  refractiveSurgery: '/images/about/refractive-surgery.webp',
  roboticSurgery: '/images/about/robotic-surgery.webp',

  // Team page
  teamHero: '/images/about/our-team-new-banner.webp',
  leadDoctor: '/images/doctors/arulmozhi-varman.webp',
  doctor1: '/images/doctors/aadithreya-varman.webp',
  doctor2: '/images/doctors/team-member-2.webp',
  doctor3: '/images/doctors/venkateshar-ravisankar.webp',
  doctor4: '/images/doctors/m-p-veenashree.webp',
  doctor5: '/images/doctors/team-member-9.webp',   // Prithi Udhay
  doctor6: '/images/doctors/team-member-10.webp',  // Uma Ramesh
  doctor7: '/images/doctors/team-member-11.webp',  // Kasinathan N
  teamAbout1: '/images/about/team/team-1.webp',
  teamAbout2: '/images/about/team/team-2.webp',
  teamAbout3: '/images/about/team/team-4.webp',
  teamAbout4: '/images/about/team/team-5.webp',

  // Optical page
  opticalHero: '/images/about/optical-showroom-banner.webp',
  opticalDesc: '/images/about/optical-showroom-2.webp',
  opticalShowroom2: '/images/about/optical-showroom-2.webp',
  opticalShowroom3: '/images/about/optical-showroom-3.webp',
  opticalPho1: '/images/about/optical-pho-1.webp',
  opticalPho2: '/images/about/optical-pho-2.webp',
  opticalPho3: '/images/about/optical-pho-3.webp',
  opticalPho4: '/images/about/optical-pho-4.webp',

  // Foundation page
  foundationBanner: '/images/about/vision-foundation-banner.webp',
  foundation1: '/images/about/social-venture/social-1.webp',
  foundation2: '/images/about/social-venture/social-2.webp',
  foundation3: '/images/about/social-venture/social-3.webp',
  social21: '/images/about/social-venture/social-21.webp',
  social22: '/images/about/social-venture/social-22.webp',
  social23: '/images/about/social-venture/social-23.webp',
  social24: '/images/about/social-venture/social-24.webp',

  // Treatments offered
  treatmentsBanner: '/images/about/treatments-offered-banner.webp',

  // Training page
  trainingHero: '/images/about/about-banner.webp',
  instructor: '/images/doctors/arulmozhi-varman.webp',
  trainingProg: '/images/about/investigate-1.webp',
  schoolVision: '/images/home/vision-1.webp',

  // Blog page
  blogBanner: '/images/blog/blog-banner.webp',
  blog1: '/images/blogs/thumb/1733224923_2c1863531d92dfa81f04.webp',
  blog2: '/images/blogs/thumb/1733227722_dea038321e37af048332.webp',
  blog3: '/images/blogs/thumb/1733228708_7bb6eebe4e26c457d4c1.webp',
  blog4: '/images/blogs/thumb/1736489096_4e1a4a85567779f51e15.webp',
  blog5: '/images/blogs/thumb/1733224923_2c1863531d92dfa81f04.webp',
  blog6: '/images/blogs/thumb/1733227722_dea038321e37af048332.webp',

  // Videos page
  videoBanner: '/images/video/video-banner.webp',
  videoDot1: '/images/video/dot-1.webp',
  videoDot2: '/images/video/dot-2.webp',
  videoThumb: '/images/video/video-1.webp',

  // FAQ page
  faqBanner: '/images/about/faq-banner.webp',

  // International page
  internationalBanner: '/images/international/international-banner.webp',
  intlIcon1: '/images/international/icon-1.webp',
  intlIcon2: '/images/international/icon-2.webp',
  intlIcon3: '/images/international/icon-3.webp',
  intlCall: '/images/international/call.webp',
  intlMail: '/images/international/mail.webp',
  intlMap: '/images/international/map.webp',

  // SMILE PRO service
  smileProBanner: '/images/services/smile-pro/smile-pro-banner.webp',
  smileImg: '/images/services/smile-pro/smile-img.webp',
  smile1: '/images/services/smile-pro/smile-1.webp',
  smile2: '/images/services/smile-pro/smile-2.webp',
  smile3: '/images/services/smile-pro/smile-3.webp',
  smile4: '/images/services/smile-pro/smile-4.webp',
  smile5: '/images/services/smile-pro/smile-5.webp',
  smile6: '/images/services/smile-pro/smile-6.webp',
  smile7: '/images/services/smile-pro/smile-7.webp',
  smileReview: '/images/services/smile-pro/smile-review.webp',
  smileTestimonial: '/images/services/smile-pro/testiminial-main.webp',
  smileLiWhy: '/images/services/smile-pro/li-why.webp',
  smileFemale: '/images/services/smile-pro/sm-female.webp',
  smileMale: '/images/services/smile-pro/sm-male.webp',
  smileMoreVideo1: '/images/services/smile-pro/more-video-1.webp',
  smileMoreVideo2: '/images/services/smile-pro/more-video-2.webp',
  smileMoreVideo3: '/images/services/smile-pro/more-video-3.webp',
  smileMoreVideo4: '/images/services/smile-pro/more-video-4.webp',
  smileMoreVideo5: '/images/services/smile-pro/more-video-5.webp',
  smileMoreVideo6: '/images/services/smile-pro/more-video-6.webp',

  // Cataract service
  cataractBanner: '/images/services/cataract/cataract-banner.webp',
  cataractRight: '/images/services/cataract/cataract-right.webp',
  procedure1: '/images/services/cataract/procedure-1.webp',
  procedure2: '/images/services/cataract/procedure-2.webp',
  procedure3: '/images/services/cataract/procedure-3.webp',

  // Presbyond service
  presbyondBanner: '/images/presbyond/presbyond-banner.webp',
  presbyondWork: '/images/presbyond/presbyond-work.webp',
  presbyondExperiance: '/images/presbyond/presbyond-experiance.webp',
  preBino1: '/images/presbyond/pre-bino-1.svg',
  preBino2: '/images/presbyond/pre-bino-2.svg',

  // LASIK service
  lasikBanner: '/images/services/lasik/lasik-banner.webp',
  lasikRight: '/images/services/lasik/lasik-right.webp',
  lasikEye: '/images/services/lasik/lasik-eye.webp',
  lasikIcon1: '/images/services/lasik/icon-1.webp',
  lasikIcon2: '/images/services/lasik/icon-2.webp',
  lasikIcon3: '/images/services/lasik/icon-3.webp',

  // Glaucoma service
  glaucomaBanner: '/images/services/glaucoma/glaucoma-banner.webp',
  glaucomaRight: '/images/services/glaucoma/glaucoma-right.webp',
  glaucomaEye: '/images/services/glaucoma/glaucoma-eye.webp',
  glaucomaIcon1: '/images/services/glaucoma/icon-1.webp',
  glaucomaIcon2: '/images/services/glaucoma/icon-2.webp',
  glaucomaIcon3: '/images/services/glaucoma/icon-3.webp',
  glaucomaIcon4: '/images/services/glaucoma/icon-4.webp',

  // Corneal Grafting service
  cornealGraftingBanner: '/images/services/corneal-grafting/corneal-grafting-banner.webp',
  cornealGraftingRight: '/images/services/corneal-grafting/corneal-grafting-right.webp',
  cornealGraftingRight2: '/images/services/corneal-grafting/corneal-grafting-right-2.webp',
  cornealGraftingIcon1: '/images/services/corneal-grafting/icon-1.webp',
  cornealGraftingIcon2: '/images/services/corneal-grafting/icon-2.webp',
  cornealGraftingIcon3: '/images/services/corneal-grafting/icon-3.webp',
  cornealGraftingIcon4: '/images/services/corneal-grafting/icon-4.webp',

  // Diabetic Retinopathy service
  diabeticBanner: '/images/services/diabetic-retinopathy/diabetic-retinopathy-banner.webp',
  diabeticRight: '/images/services/diabetic-retinopathy/diabetic-retinopathy-right.webp',
  diabeticEye: '/images/services/diabetic-retinopathy/diabetic-retinopathy-eye.webp',

  // Dry Eyes service
  dryEyesBanner: '/images/services/dry-eyes/dry-eyes-banner.webp',
  dryEyesRight: '/images/services/dry-eyes/dry-eyes-right.webp',
  dryEyesEye: '/images/services/dry-eyes/dry-eyes-eye.webp',

  // Retina & Vitreous service
  retinaVitreousBanner: '/images/services/retina-vitreous-disorders/retina-vitreous-disorders-banner.webp',
  retinaVitreousRight: '/images/services/retina-vitreous-disorders/retina-vitreous-disorders-right.webp',
  retinaVitreousRight2: '/images/services/retina-vitreous-disorders/retina-vitreous-disorders-right-2.webp',

  // Squint service
  squintBanner: '/images/services/squint-oculomotor-disorders/squint-oculomotor-disorders-banner.webp',
  squintRight: '/images/services/squint-oculomotor-disorders/squint-oculomotor-disorders-right.webp',
  squintEye: '/images/services/squint-oculomotor-disorders/squint-oculomotor-disorders-eye.webp',

  // Contact Lenses service
  contactLenseBanner: '/images/services/contact-lense/contact-lense-banner.webp',
  contactLenseRight: '/images/services/contact-lense/contact-lense-right.webp',
  lense1: '/images/services/contact-lense/lense-1.webp',
  lense2: '/images/services/contact-lense/lense-2.webp',
  symptoms1: '/images/services/contact-lense/symptoms-1.webp',
  symptoms2: '/images/services/contact-lense/symptoms-2.webp',
  symptoms3: '/images/services/contact-lense/symptoms-3.webp',
  symptoms4: '/images/services/contact-lense/symptoms-4.webp',
  symptoms5: '/images/services/contact-lense/symptoms-5.webp',

  // WhatsApp icon
  whatsappIcon: '/images/watsapp-icon.webp',
}

// Video thumbnails for Videos page
export const VIDEO_THUMBNAILS = [
  { src: '/images/media/thumb/video-1.webp', title: 'Video 1' },
  { src: '/images/media/thumb/video-2.webp', title: 'Video 2' },
  { src: '/images/media/thumb/video-4.webp', title: 'Video 4' },
  { src: '/images/media/thumb/video-5.webp', title: 'Video 5' },
  { src: '/images/media/thumb/video-6.webp', title: 'Video 6' },
  { src: '/images/media/thumb/video-7.webp', title: 'Video 7' },
  { src: '/images/media/thumb/video-8.webp', title: 'Video 8' },
  { src: '/images/media/thumb/video-9.webp', title: 'Video 9' },
  { src: '/images/media/thumb/video-10.webp', title: 'Video 10' },
  { src: '/images/media/thumb/video-11.webp', title: 'Video 11' },
  { src: '/images/media/thumb/video-12.webp', title: 'Video 12' },
  { src: '/images/media/thumb/video-13.webp', title: 'Video 13' },
  { src: '/images/media/thumb/video-14.webp', title: 'Video 14' },
  { src: '/images/media/thumb/video-15.webp', title: 'Video 15' },
  { src: '/images/media/thumb/video-16.webp', title: 'Video 16' },
  { src: '/images/media/thumb/video-17.webp', title: 'Video 17' },
  { src: '/images/media/thumb/video-19.webp', title: 'Video 19' },
  { src: '/images/media/thumb/video-20.webp', title: 'Video 20' },
  { src: '/images/media/thumb/video-21.webp', title: 'Video 21' },
  { src: '/images/media/thumb/video-22.webp', title: 'Video 22' },
  { src: '/images/media/thumb/video-23.webp', title: 'Video 23' },
  { src: '/images/media/thumb/video-24.webp', title: 'Video 24' },
  { src: '/images/media/thumb/video-25.webp', title: 'Video 25' },
  { src: '/images/media/thumb/video-26.webp', title: 'Video 26' },
  { src: '/images/media/thumb/video-27.webp', title: 'Video 27' },
  { src: '/images/media/thumb/video-28.webp', title: 'Video 28' },
  { src: '/images/media/thumb/video-29.webp', title: 'Video 29' },
  { src: '/images/media/thumb/video-30.webp', title: 'Video 30' },
  { src: '/images/media/thumb/video-31.webp', title: 'Video 31' },
  { src: '/images/media/thumb/video-32.webp', title: 'Video 32' },
  { src: '/images/media/thumb/video-33.webp', title: 'Video 33' },
  { src: '/images/media/thumb/video-34.webp', title: 'Video 34' },
  { src: '/images/media/thumb/video-35.webp', title: 'Video 35' },
  { src: '/images/media/thumb/video-36.webp', title: 'Video 36' },
  { src: '/images/media/thumb/video-37.webp', title: 'Video 37' },
  { src: '/images/media/thumb/video-38.webp', title: 'Video 38' },
  { src: '/images/media/thumb/video-39.webp', title: 'Video 39' },
  { src: '/images/media/thumb/video-40.webp', title: 'Video 40' },
  { src: '/images/media/thumb/video-41.webp', title: 'Video 41' },
  { src: '/images/media/thumb/video-112.webp', title: 'Video 112' },
  { src: '/images/media/thumb/video-113.webp', title: 'Video 113' },
  { src: '/images/media/thumb/video-120.webp', title: 'Video 120' },
  { src: '/images/media/thumb/video-img.webp', title: 'Featured Video' },
  { src: '/images/media/thumb/smile-pro-8.webp', title: 'SMILE PRO' },
  { src: '/images/media/thumb/smile-lasik.webp', title: 'SMILE vs LASIK' },
  { src: '/images/media/thumb/smile-icl.webp', title: 'SMILE ICL' },
  { src: '/images/media/thumb/smile-vs-lasik.webp', title: 'SMILE vs LASIK Comparison' },
  { src: '/images/media/thumb/smile-pro-laser.webp', title: 'SMILE PRO Laser' },
  { src: '/images/media/thumb/laser.webp', title: 'Laser Treatment' },
  { src: '/images/media/thumb/laser-surgery.webp', title: 'Laser Surgery' },
  { src: '/images/media/thumb/laser-eye-surgery.webp', title: 'Laser Eye Surgery' },
  { src: '/images/media/thumb/laser-correction.webp', title: 'Laser Correction' },
  { src: '/images/media/thumb/laser-vision-correction.webp', title: 'Laser Vision Correction' },
  { src: '/images/media/thumb/laser-cataract-surgery-in-10-mins.webp', title: 'Laser Cataract Surgery in 10 Mins' },
  { src: '/images/media/thumb/advance-laser-correction.webp', title: 'Advanced Laser Correction' },
  { src: '/images/media/thumb/best-laser-procedure.webp', title: 'Best Laser Procedure' },
  { src: '/images/media/thumb/cataract.webp', title: 'Cataract' },
  { src: '/images/media/thumb/live-cataract.webp', title: 'Live Cataract Surgery' },
  { src: '/images/media/thumb/what-is-cataract.webp', title: 'What is Cataract?' },
  { src: '/images/media/thumb/10-facts-about-cataract.webp', title: '10 Facts About Cataract' },
  { src: '/images/media/thumb/types-of-cataract-surgery-lens.webp', title: 'Types of Cataract Surgery Lens' },
  { src: '/images/media/thumb/robotic.webp', title: 'Robotic Surgery' },
  { src: '/images/media/thumb/presbyond.webp', title: 'Presbyond' },
  { src: '/images/media/thumb/diabetic.webp', title: 'Diabetic Eye Care' },
  { src: '/images/media/thumb/macular.webp', title: 'Macular Treatment' },
  { src: '/images/media/thumb/patient-testimonial.webp', title: 'Patient Testimonial' },
  { src: '/images/media/thumb/patient-testimonials.webp', title: 'Patient Testimonials' },
  { src: '/images/media/thumb/patient.webp', title: 'Patient Story' },
  { src: '/images/media/thumb/patient-test.webp', title: 'Patient Test' },
  { src: '/images/media/thumb/happy-patent.webp', title: 'Happy Patient' },
  { src: '/images/media/thumb/happy.webp', title: 'Happy' },
  { src: '/images/media/thumb/feedback.webp', title: 'Feedback' },
  { src: '/images/media/thumb/feedback-ici.webp', title: 'Feedback ICI' },
  { src: '/images/media/thumb/farina-azad.webp', title: 'Farina Azad' },
  { src: '/images/media/thumb/pavithra.webp', title: 'Pavithra' },
  { src: '/images/media/thumb/transforming-lives.webp', title: 'Transforming Lives' },
  { src: '/images/media/thumb/1000-smile.webp', title: '1000 SMILE' },
  { src: '/images/media/thumb/eye-care.webp', title: 'Eye Care' },
  { src: '/images/media/thumb/eye-doctor.webp', title: 'Eye Doctor' },
  { src: '/images/media/thumb/eye-care-during-this-covid-era.webp', title: 'Eye Care During COVID' },
  { src: '/images/media/thumb/free-vision.webp', title: 'Free Vision' },
  { src: '/images/media/thumb/glass-free-reading.webp', title: 'Glass Free Reading' },
  { src: '/images/media/thumb/glass-free-vision.webp', title: 'Glass Free Vision' },
  { src: '/images/media/thumb/go-spectacle-free.webp', title: 'Go Spectacle Free' },
  { src: '/images/media/thumb/spectacle.webp', title: 'Spectacle' },
  { src: '/images/media/thumb/correct-lens.webp', title: 'Correct Lens' },
  { src: '/images/media/thumb/premium.webp', title: 'Premium' },
  { src: '/images/media/thumb/procedures.webp', title: 'Procedures' },
  { src: '/images/media/thumb/advantage.webp', title: 'Advantage' },
  { src: '/images/media/thumb/best-option.webp', title: 'Best Option' },
  { src: '/images/media/thumb/blade-vs-bladeless.webp', title: 'Blade vs Bladeless' },
  { src: '/images/media/thumb/10-things.webp', title: '10 Things to Know' },
  { src: '/images/media/thumb/advances-ai.webp', title: 'Advances in AI' },
  { src: '/images/media/thumb/ultimate-technology.webp', title: 'Ultimate Technology' },
  { src: '/images/media/thumb/coronavirus-pandemic.webp', title: 'Coronavirus Pandemic' },
  { src: '/images/media/thumb/live-against-covid.webp', title: 'Live Against COVID' },
  { src: '/images/media/thumb/live-procedure.webp', title: 'Live Procedure' },
  { src: '/images/media/thumb/live-surgery.webp', title: 'Live Surgery' },
  { src: '/images/media/thumb/good-to-pour-oil.webp', title: 'Good to Pour Oil?' },
  { src: '/images/media/thumb/is-it-good-to-pour.webp', title: 'Is It Good to Pour?' },
  { src: '/images/media/thumb/ungal.webp', title: 'Ungal' },
  { src: '/images/media/thumb/faq.webp', title: 'FAQ' },
]
